import { useRef, useState } from "preact/hooks";
import type { ComponentChildren } from "preact";
import { api, type Issue, type Activity, type IssueTree } from "../api.js";
import { inspectorParent, inspectorStatusAction } from "../inspector.js";
import { issueEditorShortcut, commentSubmitShortcut } from "../keyboard.js";
import { issueSidebarCollapsed, issueSidebarStorage, rememberIssueSidebar } from "../sidebar.js";
import { activityValues } from "../presentation.js";
import { nextSortValue, sortState } from "../listings.js";
import { type Route } from "../routing/route.js";
import { Button, ErrorMessage, Loading, Markdown, useApp, useResource, useMutation, Time, Avatar, Popover, confirmMutation, NameLink } from "../components/ui.js";
import { Autocomplete } from "../components/autocomplete.js";
import { IssueFields, issueFields, FilePicker, RelationFields } from "../components/issue-form.js";
import { IssueTable, IssueBadges, Badge } from "../components/issues.js";

export function IssuePage({route}:{route:Route}) {
  const id=decodeURIComponent(route.path[1]);
  const resource=useResource(async()=>{const [issue,activity,children]=await Promise.all([api.issue(id),api.activity(id),api.issues({parent:id,"include-closed":true,"include-archived":true})]);const workspace=await api.workspace(issue.workspace);return {issue,activity:activity.rows,children:children.rows,workspace};},[id]);
  const [editing,setEditing]=useState(false);const [collapsed,setCollapsed]=useState(()=>issueSidebarCollapsed(issueSidebarStorage(window)));
  const editButton=useRef<HTMLButtonElement>(null);
  if(!resource.data)return <><ErrorMessage error={resource.error}/>{!resource.error&&<Loading/>}</>;
  const {issue,activity,children,workspace}=resource.data;const mutable=workspace.state==="active";
  const hide=()=>{setEditing(false);editButton.current?.focus({preventScroll:true});};
  return <div class={`issue-view ${collapsed?"sidebar-collapsed":""} ${editing?"issue-editing":""} ${mutable?"":"archived-workspace-issue"}`} onKeyDown={e=>{if(!e.defaultPrevented&&editing&&issueEditorShortcut(e)==="hide"){e.preventDefault();hide();}}}>
    <div class="issue-content">{!mutable&&<div class="workspace-archive-banner issue-archive-banner" role="status"><strong>Read-only</strong>Workspace {workspace.key} is archived.</div>}
      <div class="issue-heading"><div class="issue-heading-text"><div class="issue-key">{issue.id}</div><h1>{issue.title}</h1></div>{mutable&&<Button ref={editButton} onClick={()=>setEditing(!editing)}>{editing?"Hide editor":"Edit issue"}</Button>}</div>
      <ErrorMessage error={resource.error}/>
      {editing&&mutable&&<IssueEditor issue={issue} reload={resource.reload}/>}
      <section class="issue-description"><h2>Description</h2>{issue.description?<Markdown text={issue.description} className="issue-description-body"/>:<p class="empty">No description.</p>}</section>
      {children.length>0&&<Children parent={issue.id} issues={children} mutable={mutable} reload={resource.reload}/>}
      <Resources issue={issue} editing={editing&&mutable} reload={resource.reload}/>
      <a class="action" href={`#/tree/${issue.id}`}>Show the decomposition below this issue</a>
      <ActivitySection issue={issue.id} entries={activity} mutable={mutable} reload={resource.reload}/>
    </div><IssueSidebar issue={issue} mutable={mutable} reload={resource.reload}/><Button class="issue-sidebar-toggle" aria-controls="issue-details" aria-label={collapsed?"Show issue details":"Hide issue details"} title={collapsed?"Show issue details":"Hide issue details"} aria-expanded={!collapsed} onClick={()=>{rememberIssueSidebar(issueSidebarStorage(window),!collapsed);setCollapsed(!collapsed);}}>ⓘ</Button>
  </div>;
}
function IssueEditor({issue,reload}:{issue:Issue;reload:()=>Promise<void>}) {
  const mutation=useMutation();const [saved,setSaved]=useState(false);
  return <form class="edit-panel issue-edit-form" onInput={()=>setSaved(false)} onKeyDown={e=>{if(issueEditorShortcut(e)==="save"){e.preventDefault();e.currentTarget.requestSubmit();}}} onSubmit={e=>{e.preventDefault();const patch=issueFields(e.currentTarget);void mutation.run(async()=>{await api.updateIssue(issue.id,patch);await reload();setSaved(true);});}}><h2>Edit issue</h2><IssueFields issue={issue}/><ErrorMessage error={mutation.error}/><div class="edit-actions"><span class="edit-shortcut-hint">Esc to hide · Ctrl/⌘+Enter to save</span>{saved&&<span role="status">Saved.</span>}<Button type="submit" class="primary-button" disabled={mutation.busy}>Save changes</Button></div></form>;
}
function Children({parent,issues,mutable,reload}:{parent:string;issues:Issue[];mutable:boolean;reload:()=>Promise<void>}) {
  const key=`awb.issue.${parent}.show-closed-children`;
  const [closed,setClosed]=useState(()=>{try{return localStorage.getItem(key)!=="false";}catch{return true;}});
  const [sort,setSort]=useState<string|null>(null);const mutation=useMutation();
  const keys=["id","type","priority","status","assignee"];const state=sortState(sort,keys,"order");
  const rows=issues.filter(i=>closed||i.status!=="closed");
  if(state.explicit){const value=(i:Issue):string|number=>state.key==="priority"?i.priority:state.key==="type"?["epic","feature","bug","task","chore"].indexOf(i.type):state.key==="status"?["open","in_progress","closed"].indexOf(i.status):state.key==="assignee"?i.assignees.join(","):i.id;rows.sort((a,b)=>{const x=value(a),y=value(b);if(state.key==="assignee"&&(x===""||y==="")&&x!==y)return x===""?1:-1;return (typeof x==="number"&&typeof y==="number"?x-y:String(x).localeCompare(String(y)))*(state.direction==="asc"?1:-1)||a.id.localeCompare(b.id);});}
  return <section class="issue-resource-section child-issues-section"><div class="child-issues-heading"><h2>Child issues</h2><label class="include-closed-control"><input type="checkbox" checked={closed} onChange={e=>{setClosed(e.currentTarget.checked);try{localStorage.setItem(key,String(e.currentTarget.checked));}catch{/* optional preference */}}}/>Show closed</label></div><ErrorMessage error={mutation.error}/><IssueTable issues={rows} children mutable={mutable} sortKey={state.key} direction={state.direction} onSort={key=>setSort(nextSortValue(sort,key,keys,"order"))} onReload={reload} actions={mutable?child=><Button class="inline-button danger-button resource-remove" disabled={mutation.busy} onClick={async e=>{if(await confirmMutation("Remove child?",`Remove ${child.id} from ${parent}?`,e.currentTarget,true))void mutation.run(async()=>{await api.issue(child.id);await api.removeRelation(child.id,"has-parent",parent);await reload();});}}>Remove</Button>:undefined}/></section>;
}
function Resources({issue,editing,reload}:{issue:Issue;editing:boolean;reload:()=>Promise<void>}) {
  const mutation=useMutation();const relations=issue.relations.filter(r=>r.type!=="has-parent");
  const change=(operation:()=>Promise<unknown>)=>mutation.run(async()=>{await operation();await reload();});
  return <><ErrorMessage error={mutation.error}/>{(editing||issue.attachments.length>0)&&<section class="issue-resource-section issue-attachments"><h2>Attachments</h2><ul class="attachments resource-list">{issue.attachments.map(a=><li key={a.name}><a href={`api/issues/${encodeURIComponent(a.issue)}/attachments/${encodeURIComponent(a.name)}/content`}>{a.name}</a><span class="size">{formatSize(a.size)}</span><span class="content-type">{a.content_type}</span>{editing&&<Button class="inline-button danger-button resource-remove" disabled={mutation.busy} onClick={async e=>{if(await confirmMutation("Remove attachment?",`Remove ${a.name} from ${a.issue}.`,e.currentTarget,true))void change(()=>api.removeAttachment(a.issue,a.name));}}>Remove</Button>}</li>)}</ul>{editing&&<FilePicker onFiles={files=>void change(async()=>{for(const file of files)await api.addAttachment(issue.id,file);})}/>}</section>}
    {(editing||relations.length>0)&&<section class="issue-resource-section issue-relations"><h2>Relations</h2><ul class="relations resource-list">{relations.map(r=><li key={`${r.type}:${r.other}:${r.direction}`}><span class="relation-type">{r.direction==="in"?`← ${r.type}`:r.type}</span><a class="id" href={`#/issues/${r.other}`}>{r.other}</a>{editing&&<Button class="inline-button danger-button resource-remove" disabled={mutation.busy} onClick={async e=>{if(await confirmMutation("Remove relation?",`Remove ${r.type} relation with ${r.other}?`,e.currentTarget,true))void change(async()=>{const subject=r.direction==="in"?r.other:issue.id;await api.issue(subject);return api.removeRelation(subject,r.type,r.direction==="in"?issue.id:r.other);});}}>Remove</Button>}</li>)}</ul>{editing&&<RelationFields onAdd={(type,other)=>void change(()=>api.addRelation(issue.id,{type,other,force:false}))}/>}</section>}</>;
}
function formatSize(size:number) {const units=["B","KiB","MiB","GiB","TiB"];let unit=0;while(size>=1024&&unit<units.length-1){size/=1024;unit++;}return `${unit?size.toFixed(1):size} ${units[unit]}`;}

function IssueSidebar({issue,mutable,reload}:{issue:Issue;mutable:boolean;reload:()=>Promise<void>}) {
  const {identity}=useApp();const mutation=useMutation();const [parentValue,setParent]=useState("");const [label,setLabel]=useState("");const [assignee,setAssignee]=useState("");const [closing,setClosing]=useState(false);
  const parent=inspectorParent(issue.relations);
  const change=(operation:()=>Promise<unknown>)=>mutation.run(async()=>{await operation();await reload();});
  const fact=(label:string,children:ComponentChildren)=><div class="issue-fact"><dt>{label}</dt><dd>{children}</dd></div>;
  return <aside class="issue-sidebar" id="issue-details" aria-label="Issue details" aria-busy={mutation.busy}><h2 class="issue-sidebar-title">Details</h2><ErrorMessage error={mutation.error}/><fieldset disabled={!mutable||mutation.busy} class="inspector-fields"><dl class="issue-facts">
    {fact("ID",<span class="id">{issue.id}</span>)}{fact("Workspace",<a href={`#/workspaces/${issue.workspace}`}>{issue.workspace}</a>)}{issue.commit_hash&&fact("Commit",<span class="id commit-hash">{issue.commit_hash}</span>)}{issue.pull_request_url&&fact("Pull request",<a href={issue.pull_request_url}>{issue.pull_request_url}</a>)}
    {fact("Parent",<span class="inspector-values parent-inspector-values">{parent?<a class="parent-link" href={`#/issues/${parent}`}>{parent}</a>:"—"}<Popover label={parent?"Change parent":"Set parent"}><form class="sidebar-editor parent-editor" onSubmit={e=>{e.preventDefault();void change(async()=>{await api.addRelation(issue.id,{type:"has-parent",other:parentValue,force:!!parent});setParent("");});}}><Autocomplete value={parentValue} onValue={setParent} aria-label="Parent issue ID" placeholder="Parent issue ID" required load={async(q,s)=>(await api.issueSuggestions(q,s)).rows.filter(i=>i.id!==issue.id).map(i=>({value:i.id,label:i.id,detail:i.title}))}/><Button type="submit" class="quiet-action">{parent?"Replace":"Set"}</Button></form></Popover>{parent&&<Button class="inspector-add inspector-remove" aria-label={`Remove parent ${parent}`} onClick={()=>void change(()=>api.removeRelation(issue.id,"has-parent",parent))}>×</Button>}</span>)}
    {fact("Type",<select class="sidebar-select" aria-label="Type" value={issue.type} onChange={e=>{const type=e.currentTarget.value as Issue["type"];e.currentTarget.value=issue.type;void change(()=>api.updateIssue(issue.id,{type}));}}>{["epic","feature","bug","task","chore"].map(t=><option key={t}>{t}</option>)}</select>)}
    {fact("Status",<><select class="sidebar-select" aria-label="Status" value={issue.status} onChange={async e=>{const target=e.currentTarget.value as Issue["status"];e.currentTarget.value=issue.status;const action=inspectorStatusAction(issue.status,target);if(action==="none")return;if(action==="close"){setClosing(true);return;}if(target==="open"&&issue.assignees.length&&!(await confirmMutation("Move to Open?",`Moving ${issue.id} to Open clears all assignees.`)))return;void change(action==="claim"?()=>api.claimIssue(issue.id,{force:issue.status==="closed"}):action==="release"?()=>api.releaseIssue(issue.id,{force:true}):()=>api.reopenIssue(issue.id));}}>{["open","in_progress","closed"].map(s=><option key={s}>{s}</option>)}</select>{closing&&<form class="close-editor" onSubmit={e=>{e.preventDefault();const reason=String(new FormData(e.currentTarget).get("reason")??"");void change(async()=>{await api.closeIssue(issue.id,reason?{reason}:{});setClosing(false);});}}><input name="reason" placeholder="Close reason (optional)" aria-label="Close reason" maxLength={500} autofocus/><Button type="submit" class="danger-button">Close</Button><Button onClick={()=>setClosing(false)}>Cancel</Button></form>}</>)}
    {fact("Priority",<select class={`sidebar-select priority p${issue.priority}`} aria-label="Priority" value={issue.priority} onChange={e=>{const priority=Number(e.currentTarget.value);e.currentTarget.value=String(issue.priority);void change(()=>api.updateIssue(issue.id,{priority}));}}>{[0,1,2,3,4].map(p=><option key={p} value={p}>P{p}</option>)}</select>)}{issue.blocked&&fact("Readiness",<Badge className="blocked">blocked</Badge>)}
    {fact("Labels",<span class="inspector-values">{issue.labels.length===0&&"—"}{issue.labels.map(item=><span class="editable-chip" key={item}><Badge className="label">{item}</Badge><Button class="chip-remove" aria-label={`Remove label ${item}`} onClick={()=>void change(()=>api.removeLabel(issue.id,item))}>×</Button></span>)}<Popover label="Add label"><form class="sidebar-editor label-editor" onSubmit={e=>{e.preventDefault();void change(async()=>{await api.addLabel(issue.id,label);setLabel("");});}}><Autocomplete value={label} onValue={setLabel} aria-label="Label" placeholder="Add label" required load={async(q,s)=>(await api.labels({},s)).rows.filter(f=>!issue.labels.includes(f.value)&&f.value.toLocaleLowerCase().includes(q.toLocaleLowerCase())).map(f=>({value:f.value,label:f.value}))}/><Button type="submit" class="quiet-action">Add</Button></form></Popover></span>)}
    {fact("Assignees",<span class="inspector-values">{issue.assignees.length===0&&"—"}{issue.assignees.map(name=><span class="editable-chip" key={name}><Badge className={name===identity?"assignee mine":"assignee"}>@{name}</Badge>{issue.status==="in_progress"&&<Button class="chip-remove" aria-label={`Release ${name}`} onClick={()=>void change(()=>api.releaseIssue(issue.id,{assignee:name,force:false}))}>×</Button>}</span>)}<Popover label={issue.assignees.length?"Add assignee":"Claim issue"}><form class="sidebar-editor" onSubmit={e=>{e.preventDefault();const force=new FormData(e.currentTarget).has("force");void change(async()=>{await api.claimIssue(issue.id,{assignee:assignee||undefined,force});setAssignee("");});}}><Autocomplete value={assignee} onValue={setAssignee} aria-label="Assignee" placeholder={identity?`Assignee (default: ${identity})`:"Assignee"} load={async(q,s)=>{const [members,users]=await Promise.all([api.workspaceMembers(issue.workspace,s),api.users({},s)]);return users.rows.filter(u=>members.rows.some(m=>m.user===u.name)&&!issue.assignees.includes(u.name)&&`${u.name} ${u.full_name}`.toLocaleLowerCase().includes(q.toLocaleLowerCase())).map(u=>({value:u.name,label:u.name,detail:u.full_name}));}}/><label class="check-field"><input name="force" type="checkbox"/>Force</label><Button type="submit" class="quiet-action">{issue.assignees.length?"Add":"Claim"}</Button></form>{issue.status==="in_progress"&&<Button class="quiet-action inspector-release-all" onClick={()=>void change(()=>api.releaseIssue(issue.id,{force:true}))}>Release all</Button>}</Popover></span>)}
    {fact("Created",<Time timestamp={issue.created_at}/>)}{fact("Updated",<Time timestamp={issue.updated_at}/>)}
  </dl></fieldset></aside>;
}
function ActivitySection({issue,entries,mutable,reload}:{issue:string;entries:Activity[];mutable:boolean;reload:()=>Promise<void>}) {
  const [filter,setFilter]=useState("all");const [body,setBody]=useState("");const mutation=useMutation();const {identity}=useApp();const textarea=useRef<HTMLTextAreaElement>(null);
  const visible=entries.filter(e=>filter==="all"||filter===e.kind);
  return <section class="activity-section"><h2>Activity</h2><div class="activity-filters">{[["all","All"],["comment","Comments"],["change","Changes"]].map(([value,label])=><Button key={value} class={filter===value?"active":""} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</Button>)}</div>{mutable&&<form class="comment-composer" onSubmit={e=>{e.preventDefault();void mutation.run(async()=>{await api.addComment(issue,body);setBody("");await reload();textarea.current?.focus({preventScroll:true});});}}><Avatar name={identity} className="composer-avatar"/><div class="comment-composer-body"><textarea ref={textarea} value={body} onInput={e=>setBody(e.currentTarget.value)} name="body" placeholder="Write a comment…" required aria-label="Comment" aria-keyshortcuts="Control+Enter Meta+Enter" onKeyDown={e=>{if(commentSubmitShortcut(e)){e.preventDefault();e.currentTarget.form?.requestSubmit();}}}/><div class="comment-composer-actions"><span class="comment-hint">Comments use Markdown. Ctrl/⌘+Enter to submit.</span><Button type="submit" class="comment-submit" disabled={mutation.busy}>Add comment</Button></div><ErrorMessage error={mutation.error}/></div></form>}<div class="activity-timeline">{visible.length?visible.map(entry=><ActivityEntry key={entry.id} entry={entry}/>):<p class="empty">{filter==="all"?"No activity yet.":`No ${filter}s yet.`}</p>}</div></section>;
}
function ActivityEntry({entry}:{entry:Activity}) {
  return <article class={`activity-entry activity-${entry.kind}`}><div class={`activity-marker activity-marker-${entry.kind}`}>{entry.kind==="comment"?<Avatar name={entry.actor}/>:"↔"}</div><div class="activity-card"><header class="activity-header"><strong class="activity-actor">{entry.actor||"system"}</strong><Time timestamp={entry.created_at}/></header>{entry.action&&<div class="activity-action">{entry.action.replaceAll("_"," ")}</div>}{entry.kind==="comment"&&<Markdown className="activity-comment-body" text={entry.body}/>} {entry.changes.length>0&&<ul class="activity-changes">{entry.changes.map((change,index)=>{const [from,to]=activityValues(change.from,change.to);return <li key={index}><span class="activity-field">{change.field}</span><code>{from}</code><span class="activity-arrow">→</span><code>{to}</code></li>;})}</ul>}</div></article>;
}
export function TreePage({route}:{route:Route}) {const resource=useResource(()=>api.tree(route.path[1]??""),[route.path[1]]);return <div><h1>Decomposition</h1><p class="lede">The whole subtree, closed children included.</p><ErrorMessage error={resource.error}/>{resource.data?<Tree node={resource.data}/>:!resource.error&&<Loading/>}</div>;}
function Tree({node,depth=0}:{node:IssueTree;depth?:number}) {return <ul class={depth===0?"tree":"tree-children"}><li class="tree-row"><NameLink href={`#/issues/${node.id}`} id={node.id} title={node.title}/><IssueBadges issue={node}/></li>{node.children.map(child=><li class="tree-child" key={child.id}><Tree node={child} depth={depth+1}/></li>)}</ul>;}
